app/user/models.py
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime, timezone

db = SQLAlchemy()

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(80), unique=True, nullable=False, index=True)
    password = db.Column(db.String(162), nullable=False)
    is_active = db.Column(db.Boolean(), default=False)
    date_created = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))
    date_updated = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))
    profile = db.relationship('Profile', back_populates='user', uselist=False)
    activation_code = db.relationship('ActivationCode', back_populates='user', uselist=False)
    password_reset_code = db.relationship('PasswordResetCode', back_populates='user', uselist=False)

class Profile(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    first_name = db.Column(db.String(100), nullable=False)
    last_name = db.Column(db.String(100), nullable=False)
    date_created = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))
    date_updated = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))
    user = db.relationship('User', back_populates='profile')

class ActivationCode(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    code = db.Column(db.String(36), nullable=False, unique=True, index=True)
    date_created = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))
    date_updated = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))
    is_active = db.Column(db.Boolean(), default=True)
    user = db.relationship('User', back_populates='activation_code')

class PasswordResetCode(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    code = db.Column(db.String(36), nullable=False, unique=True, index=True)
    date_created = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))
    date_updated = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))
    is_active = db.Column(db.Boolean(), default=True)
    user = db.relationship('User', back_populates='password_reset_code')

app/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

class UserProfileForm(FlaskForm):
    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    submit = SubmitField('Update Profile')

app/__init__.py
from flask import Flask
from flask_session import Session
from flask_migrate import Migrate
from flask_mail import Mail
from config import Config
from app.user.models import db
import logging
import os

mail = Mail()

def create_app(test_config=None):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(Config)
    
    if test_config:
        app.config.from_mapping(test_config)

    initialize_extensions(app)
    register_blueprints(app)
    setup_logging(app)

    with app.app_context():
        db.create_all()

    app_title = os.getenv('APP_TITLE')
    @app.context_processor
    def inject_app_title():
        return dict(app_title=app_title)

    return app

def initialize_extensions(app):
    db.init_app(app)
    Migrate(app, db)
    Session(app)
    mail.init_app(app)

def register_blueprints(app):
    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.user import bp as user_bp
    app.register_blueprint(user_bp)

def setup_logging(app):
    if not app.debug:
        # Set up logging to file
        logging.basicConfig(filename='app.log', level=logging.INFO,
                            format='%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]')

        # Set up logging to console
        console = logging.StreamHandler()
        console.setLevel(logging.DEBUG)
        formatter = logging.Formatter('%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]')
        console.setFormatter(formatter)
        logging.getLogger('').addHandler(console)
    else:
        logging.basicConfig(level=logging.DEBUG)

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template
from app.auth.utils import login_required

from app.main import bp

@bp.route('/')
@bp.route('/index')
@login_required
def index():
    return render_template('main/index.html')

app/user/__init__.py
from flask import Blueprint

bp = Blueprint('user', __name__, url_prefix='/user')

from app.user import routes

app/user/routes.py
from flask import (
    flash, g, redirect, render_template, session, url_for, current_app
)
from app.user.models import Profile, db
from app.user.forms import UserProfileForm
from app.auth.utils import login_required
import logging

logger = logging.getLogger(__name__)

from app.user import bp

@bp.route('/profile', methods=('GET', 'POST'))
@login_required
def profile():
    user = g.user
    profile = Profile.query.filter_by(user_id=user.id).first()

    form = UserProfileForm(obj=profile)

    if form.validate_on_submit():
        first_name = form.first_name.data
        last_name = form.last_name.data

        if profile is None:
            profile = Profile(user_id=user.id, first_name=first_name, last_name=last_name)
            db.session.add(profile)
        else:
            profile.first_name = first_name
            profile.last_name = last_name

        db.session.commit()
        flash('Profile updated successfully.', 'success')
        return redirect(url_for('main.index'))

    return render_template('user/profile.html', form=form)

app/templates/auth.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
    <head>
        <script src="{{ url_for('static', filename='js/color-modes.js') }}"></script>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}My Flask App{% endblock %} &ndash; {{ app_title }}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <style>
            .bi {
                vertical-align: -.125em;
                fill: currentColor;
            }
            .nav-scroller {
                position: relative;
                z-index: 2;
                height: 2.75rem;
                overflow-y: hidden;
            }
            .nav-scroller .nav {
                display: flex;
                flex-wrap: nowrap;
                padding-bottom: 1rem;
                margin-top: -1px;
                overflow-x: auto;
                text-align: center;
                white-space: nowrap;
                -webkit-overflow-scrolling: touch;
            }
            .btn-bd-primary {
                --bd-violet-bg: #712cf9;
                --bd-violet-rgb: 112.520718, 44.062154, 249.437846;
                --bs-btn-font-weight: 600;
                --bs-btn-color: var(--bs-white);
                --bs-btn-bg: var(--bd-violet-bg);
                --bs-btn-border-color: var(--bd-violet-bg);
                --bs-btn-hover-color: var(--bs-white);
                --bs-btn-hover-bg: #6528e0;
                --bs-btn-hover-border-color: #6528e0;
                --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
                --bs-btn-active-color: var(--bs-btn-hover-color);
                --bs-btn-active-bg: #5a23c8;
                --bs-btn-active-border-color: #5a23c8;
            }
            .bd-mode-toggle {
                z-index: 1500;
            }
            .bd-mode-toggle .dropdown-menu .active .bi {
                display: block !important;
            }
            html,
            body {
                height: 100%;
            }
            .form-signin {
                max-width: 330px;
                padding: 1rem;
            }
            .form-signin .form-floating:focus-within {
                z-index: 2;
            }
            .form-signin input[type="email"] {
                margin-bottom: -1px;
                border-bottom-right-radius: 0;
                border-bottom-left-radius: 0;
            }
            .form-signin input[type="password"] {
                margin-bottom: 10px;
                border-top-left-radius: 0;
                border-top-right-radius: 0;
            }
        </style>
    </head>
    <body class="d-flex align-items-center py-4 bg-body-tertiary">
        {% include 'partials/color-modes.html' %}
        <main class="form-signin w-100 m-auto">
            <!-- Flash messages section -->
            <div>
                {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                {% for category, message in messages %}
                <div class="alert alert-{{ 'warning' if category == 'message' else category }}" role="alert">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
                {% endwith %}
            </div>
            {% block content %}{% endblock %}
        </main>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </body>
</html>

app/templates/base.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}My Flask App{% endblock %} &ndash; {{ app_title }}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <style>
            .bd-placeholder-img {
                font-size: 1.125rem;
                text-anchor: middle;
                -webkit-user-select: none;
                -moz-user-select: none;
                user-select: none;
            }
            @media (min-width: 768px) {
                .bd-placeholder-img-lg {
                    font-size: 3.5rem;
                 }
            }
            .b-example-divider {
                width: 100%;
                height: 3rem;
                background-color: rgba(0, 0, 0, .1);
                border: solid rgba(0, 0, 0, .15);
                border-width: 1px 0;
                box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
            }
            .b-example-vr {
                flex-shrink: 0;
                width: 1.5rem;
                height: 100vh;
            }
            .bi {
                vertical-align: -.125em;
                fill: currentColor;
            }
            .nav-scroller {
                position: relative;
                z-index: 2;
                height: 2.75rem;
                overflow-y: hidden;
            }
            .nav-scroller .nav {
                display: flex;
                flex-wrap: nowrap;
                padding-bottom: 1rem;
                margin-top: -1px;
                overflow-x: auto;
                text-align: center;
                white-space: nowrap;
                -webkit-overflow-scrolling: touch;
            }
            .btn-bd-primary {
                --bd-violet-bg: #712cf9;
                --bd-violet-rgb: 112.520718, 44.062154, 249.437846;
                --bs-btn-font-weight: 600;
                --bs-btn-color: var(--bs-white);
                --bs-btn-bg: var(--bd-violet-bg);
                --bs-btn-border-color: var(--bd-violet-bg);
                --bs-btn-hover-color: var(--bs-white);
                --bs-btn-hover-bg: #6528e0;
                --bs-btn-hover-border-color: #6528e0;
                --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
                --bs-btn-active-color: var(--bs-btn-hover-color);
                --bs-btn-active-bg: #5a23c8;
                --bs-btn-active-border-color: #5a23c8;
            }
            .bd-mode-toggle {
                z-index: 1500;
            }
            .bd-mode-toggle .dropdown-menu .active .bi {
                display: block !important;
            }
        </style>
        <link href="{{ url_for('static', filename='css/sidebars.css') }}" rel="stylesheet">
    </head>
    <body>
        {% include 'partials/color-modes.html' %}
        <main class="d-flex flex-nowrap">
        <div class="d-flex flex-column flex-shrink-0 p-3 bg-body-tertiary" style="width: 280px;">
            <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
            <img src="https://placehold.co/40x32" class="px-2">
            <span class="fs-4">{{ app_title }}</span>
            </a>
            <hr>
            <ul class="nav nav-pills flex-column mb-auto">
                <li class="nav-item">
                    <a href="#" class="nav-link active" aria-current="page">
                        <svg class="bi pe-none me-2" width="16" height="16">
                            <use xlink:href="#home"/>
                        </svg>
                        Home
                    </a>
                </li>
                <li>
                    <a href="#" class="nav-link link-body-emphasis">
                        <svg class="bi pe-none me-2" width="16" height="16">
                            <use xlink:href="#speedometer2"/>
                        </svg>
                        Dashboard
                    </a>
                </li>
                <li>
                    <a href="#" class="nav-link link-body-emphasis">
                        <svg class="bi pe-none me-2" width="16" height="16">
                            <use xlink:href="#table"/>
                        </svg>
                        Orders
                    </a>
                </li>
                <li>
                    <a href="#" class="nav-link link-body-emphasis">
                        <svg class="bi pe-none me-2" width="16" height="16">
                            <use xlink:href="#grid"/>
                        </svg>
                        Products
                    </a>
                </li>
                <li>
                    <a href="#" class="nav-link link-body-emphasis">
                        <svg class="bi pe-none me-2" width="16" height="16">
                            <use xlink:href="#people-circle"/>
                        </svg>
                        Customers
                    </a>
                </li>
            </ul>
            <hr>
            <div class="dropdown">
                <a href="#" class="d-flex align-items-center link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                <img src="https://placehold.co/50x50@2x.png" alt="" width="32" height="32" class="rounded-circle me-2">
                <strong>{{ g.user.email }}</strong>
                </a>
                <ul class="dropdown-menu text-small shadow">
                    <li><a class="dropdown-item" href="{{ url_for('user.profile') }}">Profile</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('auth.change_password') }}">Change Password</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="{{ url_for('auth.logout') }}">Sign out</a></li>
                </ul>
            </div>
        </div>
        <div class="flex-grow-1 p-3">
            <div>
                {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                {% for category, message in messages %}
                <div class="alert alert-{{ 'warning' if category == 'message' else category }}" role="alert">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
                {% endwith %}
            </div>
            <main class="d-flex flex-nowrap">
                <div class="container-fluid">
                    {% block content %}{% endblock %}
                </div>
            </main>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </body>
</html>

app/templates/main/index.html
{% extends 'base.html' %}
{% block content %}

{% block header %}
<h1>{% block title %}Index{% endblock %}</h1>
{% endblock %}

{% if g.user %}
<p>Welcome back, {{ g.user.email }}!</p>
{% endif %}

{% endblock %}

app/templates/user/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            {% block header %}
            <h2 class="mb-4">{% block title %}Update Profile{% endblock %}</h2>
            {% endblock %}
            
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {{ form.hidden_tag() }}
                        <div class="mb-3">
                            {{ form.first_name.label(class="form-label") }}
                            {{ form.first_name(class="form-control") }}
                        </div>
                        <div class="mb-3">
                            {{ form.last_name.label(class="form-label") }}
                            {{ form.last_name(class="form-control") }}
                        </div>
                        <button type="submit" class="btn btn-primary">{{ form.submit.label }}</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}